### ISSUE TITLE
GTF_gtex_exonBoundaries file

### ISSUE THREAD

**Issue by paulinefx** [pablo-gar/somatic_mutations_GTEx#1]
somatic_mutations_GTEx/mutationCalling/Snakefile

Hello,

I would like to thak you for uploading your code to github, it is very helpful. I am trying to adapt your pipeline to my data for my PhD, especially for the filtering steps of the mutations. In your script somatic_mutations_GTEx/mutationCalling/Snakefile, you use a file GTF_gtex_exonBoundaries. I was wondering how it was created. I am working on hg38 and I would like to update my annotation file so it works in your pipeline.

Thanks,

Pauline

**Comment by pablo-gar** [comment]
Hi Pauline,

The exon boundary file was created by simple manipulations of the original annotation file provided by GTEx. It's a bed file, with each line containing 1 bp regions representing either the start or end of an exon, thus each exon has two lines.

You can create an exon boundary file for the annotation file used in GTEx v8 (hg38) in bash as follows:

```bash

# Download annotation GTF from GTEx
wget https://storage.googleapis.com/gtex_analysis_v8/reference/gencode.v26.GRCh38.genes.gtf

# Get exon boundaries in gtf format
grep exon gencode.v26.GRCh38.genes.gtf | awk -v FS="\t" -v OFS="\t" '{end=$5; $5=$4+1; print $0 " boundary A;"; $4=end-1; $5=end; print $0 " boundary B;"}' > exons.gtf

# Convert to bed
awk -v FS="\t" -v OFS="\t" '{print $1,$4,$5,$9,$6,$7,$9}' exons.gtf | perl -pe 's/gene_id "(ENS.+?)".+exon_number (.+?)"; boundary (\w).+?\t/\1-exon_\2-boundary_\3\t/' > exons.bed
```

This will create two files `exons.gtf` and `exons.bed`, both containing exon boundaries in their respective formats
